In [1]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50,5))
scores_pd = pd.DataFrame(scores,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index = range(1,51)
             )
scores_pd

     國文  英文   數學   地理  歷史
1    99  58   99   75  94
2    73  99   60   52  93
3    87  90   99   99  74
4    82  61   89   95  83
5    55  81   74   89  81
6    69  93   86   83  52
7    62  65   85   53  95
8    56  62   63   86  60
9    56  85   51   65  66
10   71  52   97   73  97
11   58  64   62   87  67
12   91  61   67  100  72
13   69  77   89   61  56
14   75  93   54   69  56
15   58  76   61   75  93
16   58  99   63   90  89
17   80  93   77   77  62
18  100  72   96   57  71
19   78  69   86   75  84
20   85  95   54   62  58
21   92  50   84   80  64
22   63  71   65   84  70
23   53  57   59   71  77
24   81  86   61   84  85
25   57  79   94   63  94
26   63  71   92   51  98
27   75  51   95   69  81
28   95  87   54   64  91
29   83  73   91  100  65
30  100  90   52   92  96
31   61  53   92   55  54
32   76  61   78   82  75
33   50  76   62   96  72
34   79  61   66   69  86
35   70  63   92   78  74
36   52  62   70   97  92
37   69  85   94   68  96
38   55  91   83   76  80
39   60  84   78   68  51
40   95  87   93   72  99
41   54  82   82   78  82
42   92  53   85   64  93
43   66  58   71   89  88
44   83  79   78   60  88
45   50  88   80   94  55
46   97  87   60   90  89
47   66  52   52   50  65
48   89  62   61   97  92
49   75  71   93   77  85
50   51  68  100   66  77

In [2]:
scores_pd.index.name="學號"
scores_pd.columns.name="科目"
scores_pd

科目   國文  英文   數學   地理  歷史
學號
1    99  58   99   75  94
2    73  99   60   52  93
3    87  90   99   99  74
4    82  61   89   95  83
5    55  81   74   89  81
6    69  93   86   83  52
7    62  65   85   53  95
8    56  62   63   86  60
9    56  85   51   65  66
10   71  52   97   73  97
11   58  64   62   87  67
12   91  61   67  100  72
13   69  77   89   61  56
14   75  93   54   69  56
15   58  76   61   75  93
16   58  99   63   90  89
17   80  93   77   77  62
18  100  72   96   57  71
19   78  69   86   75  84
20   85  95   54   62  58
21   92  50   84   80  64
22   63  71   65   84  70
23   53  57   59   71  77
24   81  86   61   84  85
25   57  79   94   63  94
26   63  71   92   51  98
27   75  51   95   69  81
28   95  87   54   64  91
29   83  73   91  100  65
30  100  90   52   92  96
31   61  53   92   55  54
32   76  61   78   82  75
33   50  76   62   96  72
34   79  61   66   69  86
35   70  63   92   78  74
36   52  62   70   97  92
37   69  85   94   68  96
38   55  91   83   76  80
39   60  84   78   68  51
40   95  87   93   72  99
41   54  82   82   78  82
42   92  53   85   64  93
43   66  58   71   89  88
44   83  79   78   60  88
45   50  88   80   94  55
46   97  87   60   90  89
47   66  52   52   50  65
48   89  62   61   97  92
49   75  71   93   77  85
50   51  68  100   66  77

In [3]:
display(scores_pd['國文'][:10])
scores_pd['數學'][:10]
scores_pd.info()

學號
1     99
2     73
3     87
4     82
5     55
6     69
7     62
8     56
9     56
10    71
Name: 國文, dtype: int32

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   國文      50 non-null     int32
 1   英文      50 non-null     int32
 2   數學      50 non-null     int32
 3   地理      50 non-null     int32
 4   歷史      50 non-null     int32
dtypes: int32(5)
memory usage: 1.1 KB

In [4]:
scores_pd['國文'][:10] + scores_pd['數學'][:10]

學號
1     198
2     133
3     186
4     171
5     129
6     155
7     147
8     119
9     107
10    168
dtype: int32

In [5]:
scores_pd['國文'] + scores_pd['英文'] + scores_pd['地理'] + scores_pd['歷史'] + scores_pd['數學']

學號
1     425
2     377
3     449
4     410
5     380
6     383
7     360
8     327
9     323
10    390
11    338
12    391
13    352
14    347
15    363
16    399
17    389
18    396
19    392
20    354
21    370
22    353
23    317
24    397
25    387
26    375
27    371
28    391
29    412
30    430
31    315
32    372
33    356
34    361
35    377
36    373
37    412
38    385
39    341
40    446
41    378
42    387
43    372
44    388
45    367
46    423
47    285
48    401
49    401
50    362
dtype: int32

In [9]:
#統計的實體方法,sum()
scores_pd['總分'] = scores_pd[['國文','英文','數學','地理','歷史']].sum(axis=1)
scores_pd
scores_pd['平均'] = scores_pd[['國文','英文','數學','地理','歷史']].mean(axis=1)
scores_pd

科目   國文  英文   數學   地理  歷史   總分    平均
學號
1    99  58   99   75  94  425  85.0
2    73  99   60   52  93  377  75.4
3    87  90   99   99  74  449  89.8
4    82  61   89   95  83  410  82.0
5    55  81   74   89  81  380  76.0
6    69  93   86   83  52  383  76.6
7    62  65   85   53  95  360  72.0
8    56  62   63   86  60  327  65.4
9    56  85   51   65  66  323  64.6
10   71  52   97   73  97  390  78.0
11   58  64   62   87  67  338  67.6
12   91  61   67  100  72  391  78.2
13   69  77   89   61  56  352  70.4
14   75  93   54   69  56  347  69.4
15   58  76   61   75  93  363  72.6
16   58  99   63   90  89  399  79.8
17   80  93   77   77  62  389  77.8
18  100  72   96   57  71  396  79.2
19   78  69   86   75  84  392  78.4
20   85  95   54   62  58  354  70.8
21   92  50   84   80  64  370  74.0
22   63  71   65   84  70  353  70.6
23   53  57   59   71  77  317  63.4
24   81  86   61   84  85  397  79.4
25   57  79   94   63  94  387  77.4
26   63  71   92   51  98  375  75.0
27   75  51   95   69  81  371  74.2
28   95  87   54   64  91  391  78.2
29   83  73   91  100  65  412  82.4
30  100  90   52   92  96  430  86.0
31   61  53   92   55  54  315  63.0
32   76  61   78   82  75  372  74.4
33   50  76   62   96  72  356  71.2
34   79  61   66   69  86  361  72.2
35   70  63   92   78  74  377  75.4
36   52  62   70   97  92  373  74.6
37   69  85   94   68  96  412  82.4
38   55  91   83   76  80  385  77.0
39   60  84   78   68  51  341  68.2
40   95  87   93   72  99  446  89.2
41   54  82   82   78  82  378  75.6
42   92  53   85   64  93  387  77.4
43   66  58   71   89  88  372  74.4
44   83  79   78   60  88  388  77.6
45   50  88   80   94  55  367  73.4
46   97  87   60   90  89  423  84.6
47   66  52   52   50  65  285  57.0
48   89  62   61   97  92  401  80.2
49   75  71   93   77  85  401  80.2
50   51  68  100   66  77  362  72.4

In [10]:
scores_pd['排名'] = scores_pd['總分'].rank(method='min',ascending=False)
scores_pd

科目   國文  英文   數學   地理  歷史   總分    平均    排名
學號
1    99  58   99   75  94  425  85.0   4.0
2    73  99   60   52  93  377  75.4  26.0
3    87  90   99   99  74  449  89.8   1.0
4    82  61   89   95  83  410  82.0   8.0
5    55  81   74   89  81  380  76.0  24.0
6    69  93   86   83  52  383  76.6  23.0
7    62  65   85   53  95  360  72.0  38.0
8    56  62   63   86  60  327  65.4  46.0
9    56  85   51   65  66  323  64.6  47.0
10   71  52   97   73  97  390  78.0  17.0
11   58  64   62   87  67  338  67.6  45.0
12   91  61   67  100  72  391  78.2  15.0
13   69  77   89   61  56  352  70.4  42.0
14   75  93   54   69  56  347  69.4  43.0
15   58  76   61   75  93  363  72.6  35.0
16   58  99   63   90  89  399  79.8  11.0
17   80  93   77   77  62  389  77.8  18.0
18  100  72   96   57  71  396  79.2  13.0
19   78  69   86   75  84  392  78.4  14.0
20   85  95   54   62  58  354  70.8  40.0
21   92  50   84   80  64  370  74.0  33.0
22   63  71   65   84  70  353  70.6  41.0
23   53  57   59   71  77  317  63.4  48.0
24   81  86   61   84  85  397  79.4  12.0
25   57  79   94   63  94  387  77.4  20.0
26   63  71   92   51  98  375  75.0  28.0
27   75  51   95   69  81  371  74.2  32.0
28   95  87   54   64  91  391  78.2  15.0
29   83  73   91  100  65  412  82.4   6.0
30  100  90   52   92  96  430  86.0   3.0
31   61  53   92   55  54  315  63.0  49.0
32   76  61   78   82  75  372  74.4  30.0
33   50  76   62   96  72  356  71.2  39.0
34   79  61   66   69  86  361  72.2  37.0
35   70  63   92   78  74  377  75.4  26.0
36   52  62   70   97  92  373  74.6  29.0
37   69  85   94   68  96  412  82.4   6.0
38   55  91   83   76  80  385  77.0  22.0
39   60  84   78   68  51  341  68.2  44.0
40   95  87   93   72  99  446  89.2   2.0
41   54  82   82   78  82  378  75.6  25.0
42   92  53   85   64  93  387  77.4  20.0
43   66  58   71   89  88  372  74.4  30.0
44   83  79   78   60  88  388  77.6  19.0
45   50  88   80   94  55  367  73.4  34.0
46   97  87   60   90  89  423  84.6   5.0
47   66  52   52   50  65  285  57.0  50.0
48   89  62   61   97  92  401  80.2   9.0
49   75  71   93   77  85  401  80.2   9.0
50   51  68  100   66  77  362  72.4  36.0

In [11]:
scores_pd.sort_values(by='排名')

科目   國文  英文   數學   地理  歷史   總分    平均    排名
學號
3    87  90   99   99  74  449  89.8   1.0
40   95  87   93   72  99  446  89.2   2.0
30  100  90   52   92  96  430  86.0   3.0
1    99  58   99   75  94  425  85.0   4.0
46   97  87   60   90  89  423  84.6   5.0
37   69  85   94   68  96  412  82.4   6.0
29   83  73   91  100  65  412  82.4   6.0
4    82  61   89   95  83  410  82.0   8.0
48   89  62   61   97  92  401  80.2   9.0
49   75  71   93   77  85  401  80.2   9.0
16   58  99   63   90  89  399  79.8  11.0
24   81  86   61   84  85  397  79.4  12.0
18  100  72   96   57  71  396  79.2  13.0
19   78  69   86   75  84  392  78.4  14.0
28   95  87   54   64  91  391  78.2  15.0
12   91  61   67  100  72  391  78.2  15.0
10   71  52   97   73  97  390  78.0  17.0
17   80  93   77   77  62  389  77.8  18.0
44   83  79   78   60  88  388  77.6  19.0
42   92  53   85   64  93  387  77.4  20.0
25   57  79   94   63  94  387  77.4  20.0
38   55  91   83   76  80  385  77.0  22.0
6    69  93   86   83  52  383  76.6  23.0
5    55  81   74   89  81  380  76.0  24.0
41   54  82   82   78  82  378  75.6  25.0
2    73  99   60   52  93  377  75.4  26.0
35   70  63   92   78  74  377  75.4  26.0
26   63  71   92   51  98  375  75.0  28.0
36   52  62   70   97  92  373  74.6  29.0
43   66  58   71   89  88  372  74.4  30.0
32   76  61   78   82  75  372  74.4  30.0
27   75  51   95   69  81  371  74.2  32.0
21   92  50   84   80  64  370  74.0  33.0
45   50  88   80   94  55  367  73.4  34.0
15   58  76   61   75  93  363  72.6  35.0
50   51  68  100   66  77  362  72.4  36.0
34   79  61   66   69  86  361  72.2  37.0
7    62  65   85   53  95  360  72.0  38.0
33   50  76   62   96  72  356  71.2  39.0
20   85  95   54   62  58  354  70.8  40.0
22   63  71   65   84  70  353  70.6  41.0
13   69  77   89   61  56  352  70.4  42.0
14   75  93   54   69  56  347  69.4  43.0
39   60  84   78   68  51  341  68.2  44.0
11   58  64   62   87  67  338  67.6  45.0
8    56  62   63   86  60  327  65.4  46.0
9    56  85   51   65  66  323  64.6  47.0
23   53  57   59   71  77  317  63.4  48.0
31   61  53   92   55  54  315  63.0  49.0
47   66  52   52   50  65  285  57.0  50.0

In [12]:
def format60(v:int):
    if v >= 60:
        return '及格'
    else:
        return '不及格'

scores_pd[['國文','英文','數學','地理','歷史']].style.format(format60)

In [14]:
scores_pd.style\
.highlight_between(left=0,
                   right=59,
                   color='red',
                   subset=['國文','英文','數學','地理','歷史'],
                   props='color:white;background-color:red')\
.format(precision=0,subset=['平均','排名'])

In [ ]:
scores_pd.style\
.highlight_between(left=0,
                   right=59,
                   color='red',
                   subset=['國文','英文','數學','地理','歷史'],
                   props='color:white;background-color:red')\
.format(precision=0,subset=['平均','排名']).to_excel('scores.xlsx')